openapi: 3.0.1
info:
  title: Book Shop
  description: Book CRUD API.
  version: 1.0.0
tags:
  - description: Demo
    name: demo
paths:
  /book:
    get:
      summary: Get Books
      operationId: getBooks
      tags:
        - demo
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Update a Book
      operationId: upsertBook
      tags:
        - demo
      requestBody:
        description: Book to be upserted in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        200:
          description: Book Upserted
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: book
  /book/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get Book
      operationId: getBook
      tags:
        - demo
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    delete:
      summary: Delete Books
      operationId: deleteBooks
      tags:
        - demo
      responses:
        200:
          description: successful operation
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          example: Oathbringer
        author:
          type: string
          example: Brandon Sanderson