spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:pgsql.localdev.me}:5432/${DB_NAME:testdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect